Feature/16 domain
dnd-side-project/dnd-9th-2-backend pull request #22
Opened 2023-08-08 14:16 UTC by RyuKwanKon

## Related Issue 🍃

close #16

## Description 🌴
- redis를 사용해 모임 1시간 전 알람, 긴급 소집 알람, 긴급 소집 종료 알람을 구현했습니다.
- 모임 상세 정보를 제공하는 api를 제작했습니다.
- 모임 참여 여부 확인 & 모임 참여 api를 제작했습니다.

2023-08-08 14:43 UTC, SunwoongH requested changes
고생 많으셨습니다. 코드 리뷰 확인해주시고 피드백 부탁드립니다.
그리고 command + option + L, control + option + O 한 번씩만 부탁드리겠습니다!
추후 코드 충돌이 예방될 것 같습니다 ㅎㅎ

2023-08-08 14:43 UTC, SunwoongH commented on src/main/java/org/baggle/domain/fcm/domain/FcmToken.java
> +
@Builder 애노테이션이 클래스 레벨에 적용되어 있어서 해당 생성자는 삭제해도 될 것 같습니다.

2023-08-08 14:43 UTC, SunwoongH commented on src/main/java/org/baggle/domain/fcm/service/FcmService.java
> +        return new GetFcmTokenResponseDto(result);
해당 dto에 of 메서드가 정의되어 있어서 of 메서드를 활용해도 좋을 것 같습니다.

2023-08-08 14:43 UTC, SunwoongH commented on src/main/java/org/baggle/domain/meeting/domain/Participation.java
> +    }
setter의 경우, 데이터의 변경이 이루어지기 때문에 @Setter 애노테이션을 적용하지 않고 의미있는 이름의 메서드를 정의하여 사용하는 것이 개발자의 실수를 예방할 수 있는 확률이 높아져서 효용적이라고 생각이 듭니다. 하지만 getter의 경우, 데이터의 변경이 이루어지지 않기 때문에 엔티티 클래스 레벨에 @Getter 애노테이션을 적용하여 따로 메서드 정의 없이 편리하게 사용할 수 있는 장점이 더 크다고 생각되는데 어떻게 생각하시나요?

2023-08-08 14:43 UTC, SunwoongH commented on src/main/java/org/baggle/global/error/exception/ErrorCode.java
> +    MEETING_NOT_FOUNT(HttpStatus.BAD_REQUEST, "모임 정보를 찾을 수 없습니다."),
FOUNT -> FOUND 오타를 발견했습니다!

2023-08-08 17:42 UTC, RyuKwanKon commented on src/main/java/org/baggle/domain/meeting/domain/Participation.java
> +    }
맞는 말씀입니다!! 작업 중에 언제 적은 코드인지 모르겠는데 적혀있네요... 좋은 코멘트 감사합니다!!

2023-08-09 03:49 UTC, SunwoongH approved these changes
고생 많으셨습니다 👍

2023-08-09 03:50 UTC, merged